name: FastAPI CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    runs-on: ubuntu-latest

      
    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        python-version: [3.13]

    env:
      MODE: "dev"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      TAVILY_API_KEY: ${{secrets.TAVILY_API_KEY}}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install

      - name: Run Test
        run: poetry run python -m pytest src/app_test/unit/service/storage/test_local_storage_service.py
