name: FastAPI CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    env:
      MODE: "dev"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      TAVILY_API_KEY: ${{secrets.TAVILY_API_KEY}}
      STORAGE_BUCKET: ${{secrets.STORAGE_BUCKET}}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{secrets.FIREBASE_SERVICE_ACCOUNT_JSON}}

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Debug Check Directory
        run: |
          pwd
          mkdir -p secrets
      - name: Decode Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_B64 }}" | base64 --decode > secrets/gestaltquestiondata-firebase-adminsdk-fbsvc-21f3d16399.json
          cd secrets
          ls

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
        working-directory: ./backend
      - name: Install dependencies
        run: poetry install
        working-directory: ./backend

      - name: Run Test
        run: poetry run python -m pytest src/app_test/unit/service/storage/test_local_storage_service.py
        working-directory: ./backend
