name: Node.js CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json # ✅ ensure caching works
      # Debug step to verify folder structure
      - name: Clean install
        run: |
            rm -rf node_modules package-lock.json
            npm install

      - name: List repo contents
        run: ls -R

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build --if-present

      # Optional test step
      # - name: Run tests
      #   run: npm test
